### ISSUE TITLE
Zooming in will cause the screen to zoom in, and break everything.

### ISSUE THREAD

**Issue by Hybyrn** [fligger/FateClient#1008]
Two people so far have had this issue, myself and one other person on the fate client discord, the issue is where when you zoom in with your key, the screen because permanently stuck in a zoomed state, and when you try to zoom again, nothing renders. I have found a fix to this, which is very strange and somewhat annoying when you have to do it multiple times. It might be something to do with devices or some other issue.

**Comment by fligger** [comment]
Both "arm fov" and "normal fov" get modified by the same function. I used the wrong flag to detect witch fov is currently modified.
So both fov values got modified by either the "arm or the normal fov code.

this will probably happen again B)

more info #1009
