### ISSUE TITLE
Zoom issue

### ISSUE THREAD

**Issue by RedStoneCraftGG** [fligger/FateClient#1009]
when zooming in, the render suddenly disappears unless zooming out by scrolling down.

When Zoom in, the render will be like this:
![Screenshot (1505)](https://user-images.githubusercontent.com/66346080/102440510-eea1a900-4052-11eb-9f94-127d3ea7aaea.png)

i was use both texture packs and the result is same:
![image](https://user-images.githubusercontent.com/66346080/102440843-9a4af900-4053-11eb-9ba6-574f26d97612.png)

**Comment by RedStoneCraftGG** [comment]
do have a solution for this problem?

**Comment by charlie272** [comment]
My fix is to leave the world/server and rejoin

**Comment by RedStoneCraftGG** [comment]
> My fix is to leave the world/server and rejoin

i was trying that, and still not work...

**Comment by fligger** [comment]
explained in #1008
