### ISSUE TITLE
Fate Client Injecting, but not working.

### ISSUE THREAD

**Issue by F-lame** [fligger/FateClient#1010]
Hi, whenever I try to inject the fate client nothing happens. It says it injects but the keystrokes and everything stay N/A could you help me please?

**Comment by naturecodevoid** [comment]
update the dll, and make sure your minecraft is updated too

**Comment by F-lame** [comment]
Ok, I'll see if it works.

**Comment by F-lame** [comment]
Doesn't work, still nothing,.

**Comment by F-lame** [comment]
What should I do?

**Comment by naturecodevoid** [comment]
https://aka.ms/vs/16/release/vc_redist.x64.exe
https://dotnet.microsoft.com/download/dotnet-framework/net48
install and restart computer
you also need 64x I think

**Comment by F-lame** [comment]
kk
