### ISSUE TITLE
Can't connect to any server after the Inject

### ISSUE THREAD

**Issue by athkiasaris1** [fligger/FateClient#1013]
When I inject fate client on mc I can't join servers (featured and not featured). If it helps I use the first skin on the discord

**Comment by fligger** [comment]
I have nothing to do with this error. 
Please try restarting your Game. Minecraft can be buggy sometimes!

**Comment by RedStoneCraftGG** [comment]
restart the game, then inject back before start screen show (reccomend use auto inject)
