### ISSUE TITLE
Some Thing Not Found

### ISSUE THREAD

**Issue by ItzPikachuOfficial** [fligger/FateClient#1015]
![Fate Bug No 1](https://user-images.githubusercontent.com/72186048/106105233-aa351d00-6169-11eb-8582-8826fef02f80.png)
![Fate Bug No,2](https://user-images.githubusercontent.com/72186048/106105301-c89b1880-6169-11eb-9347-cbd2807aa9d3.png)
![Fate Bug No 3](https://user-images.githubusercontent.com/72186048/106105362-e10b3300-6169-11eb-9379-e73c3f07e7d6.png)
**Some Files Are Missing Please Fix It.**

**Comment by fligger** [comment]
https://github.com/fligger/FateInjector#troubleshooting
