### ISSUE TITLE
N/A Everything!

### ISSUE THREAD

**Issue by ghost** [fligger/FateClient#1016]
Hey.
This may be a problem with my injector (BootJector), but once I inject, all modules say "N/A" and cannot be toggled. I did follow your directions, I already have all versions of VC installed, still nothing.
Any help? Thanks,
Acai

**Comment by ItzPikachuOfficial** [comment]
This means fate is not injected

**Comment by fligger** [comment]
Use my injector or add the "ALL APPLICATION PACKAGES" Permission yourself [More info](https://www.unknowncheats.me/forum/general-programming-and-reversing/177183-basic-intermediate-techniques-uwp-app-modding.html)

Also #3

**Comment by fligger** [comment]
Use my injector or add the "ALL APPLICATION PACKAGES" Permission yourself [More info](https://www.unknowncheats.me/forum/general-programming-and-reversing/177183-basic-intermediate-techniques-uwp-app-modding.html)
