### ISSUE TITLE
Crashing after inject.

### ISSUE THREAD

**Issue by Ivyish** [fligger/FateClient#1020]
Minecraft just received an update, I tried injecting fate into the game then immediately crashed. It's been working fine before the update. Don't know if this is an issue within the game or fate client itself.

I used other clients and all have the same issue, it's something within the new Minecraft update. I hope they patch this because I play controller and I need the autosprint.

**Comment by 98329232** [comment]
the same happens to me

**Comment by BigFatD0NUT** [comment]
I wont be playing Minecraft until they patch it, as I use toggle sprint.

**Comment by 98329232** [comment]
> I wont be playing Minecraft until they patch it, as I use toggle sprint.

When will they patch it? Do u reckon,

**Comment by Ivyish** [comment]
> > I wont be playing Minecraft until they patch it, as I use toggle sprint.
> 
> When will they patch it? Do u reckon,

Either people find a way around injecting things into the game, or we just have to wait for a bug fix from Mojang. Depending on how many people report this, might take weeks or months. Hopefully not.

**Comment by BigFatD0NUT** [comment]
im pretty sure this is fate client not being able to handle the new update not vice versa

**Comment by 98329232** [comment]
> im pretty sure this is fate client not being able to handle the new update not vice versa

What’s that meant to mean?

**Comment by Ivyish** [comment]
> im pretty sure this is fate client not being able to handle the new update not vice versa

It's possible I guess, but I've tried injecting anything into the game. The second something gets injected it crashes. whenever it crashes it opens Windows Problem Reporting in the task manager.

**Comment by 98329232** [comment]
> > im pretty sure this is fate client not being able to handle the new update not vice versa
> 
> It's possible I guess, but I've tried injecting anything into the game. The second something gets injected it crashes. whenever it crashes it opens Windows Problem Reporting in the task manager.

The exact thing happens to me since the up date

**Comment by 98329232** [comment]
Can someone who works on it just answer are questions pls?

**Comment by Ivyish** [comment]
> Can someone who works on it just answer are questions pls?

our*

**Comment by BigFatD0NUT** [comment]
its that none of the things you are injecting are updated to the current veersion

**Comment by Mohy33** [comment]
this bug is due to fate client being outdated or "old" as the new version of minecraft bedrock doesnt support it, we will just have to wait for fligger to update it

**Comment by Mohy33** [comment]
> Can someone who works on it just answer are questions pls?

i dont work on fate client but i have seen a closed issue with the same problem, its just that fate is outdated for 1.16.210 and needs updating



> > im pretty sure this is fate client not being able to handle the new update not vice versa
> 
> It's possible I guess, but I've tried injecting anything into the game. The second something gets injected it crashes. whenever it crashes it opens Windows Problem Reporting in the task manager.

**Comment by Mohy33** [comment]
also, fligger or the creator of fateclient says it is just a hobby project so either we get an updated version of fate or not is up to them

**Comment by Ivyish** [comment]
Fligger has updated the client and it's working fine!!!!

**Comment by 98329232** [comment]
> Fligger has updated the client and it's working fine!!!!

Where do we get the updated version
