### ISSUE TITLE
I want the FATE client to match Minecraft 1.16.220

### ISSUE THREAD

**Issue by Pengdor2** [fligger/FateClient#1025]
There's some problem

I have to upload a video on YouTube, but the client doesn't work, so I can't upload the video, and other people can't use the client, so we can't play minecraft

and also we want fate client asap

**Comment by fligger** [comment]
Duplicate #1023

you can use a tool like [MCLauncher](https://github.com/MCMrARM/mc-w10-version-launcher#prerequisites) to downgrade the games version.

**Comment by Pengdor2** [comment]
Thanks

2021년 4월 15일 (목) 오전 6:01, Fligger ***@***.***>님이 작성:
