### ISSUE TITLE
this is not an issue but just a simple request 

### ISSUE THREAD

**Issue by aaryamanm128** [fligger/FateClient#1031]
recently 1.17.0 just released so can someone make a dll file for it ? idk I'm new maybe it is more complicated than that .
since when i try the latest release (1.16.210) . it will not work because the dll file is outdated it just showed that the file is injected ..BUT    
it will showing N/A when you when you open the fate settings and it will just vannila mc

**Comment by fligger** [comment]
code for dll currently is closed source
