### ISSUE TITLE
some times the gui is gliching out if we long press it and let go of it (it will show it as we are pressing it but we are not)

### ISSUE THREAD

**Issue by srmdev** [fligger/FateClient#2]
![image](https://user-images.githubusercontent.com/68980580/97847753-1abcd100-1d16-11eb-835f-580e2bad95ae.png)

**Comment by fligger** [comment]
This also occurred to me while first coding the the keystrokes module. Currently I am using the best (to me known) key values the game provides. Sadly this should be more a game problem then a problem I can fix.
