### ISSUE TITLE
Na after inject

### ISSUE THREAD

**Issue by Luckyrc** [fligger/FateClient#3]
I watched videos and did everything like it says but after I inject it it says na on everything

**Comment by fligger** [comment]
Basically some people can't get the client to load correctly. 

They have everything Installed correctly.
The DLL file has the "ALL APPLICATION PACKAGES" permission
but the injecting process still messes up at some point.

I did try out different injectors and different injection methods using [Extreme Injector](https://github.com/master131/ExtremeInjector) but still no luck.

I don't know how to fix this :|

**Comment by fligger** [comment]
This seems to help people!

1. Go to https://support.microsoft.com/de-de/help/2977003/the-latest-supported-visual-c-downloads
2. Scroll down and download the x64: vc_redist.x64.exe
3. Run the exe and install it
4. Restart PC after install
5. Fate should now work

**Comment by phsax** [comment]
still doesn't work

**Comment by Ad-0934** [comment]
for the new modified gui is n/a when I inject the dll but when i load a world i could see the keystrokes but cannot customize it
