### ISSUE TITLE
Please add option to disable extra paper doll! (Suggestion)

### ISSUE THREAD

**Issue by ASOwnerYT** [fligger/FateClient#4]
Can you please add an option to Fate Client settings to disable this new paper doll at the top right? See screenshot if you don't know what I mean. 
![image](https://user-images.githubusercontent.com/23545044/98433746-cf982900-212e-11eb-92cb-faa665b77593.png)

**Comment by ItzLightyHD** [comment]
Try the new texture

**Comment by srmdev** [comment]
use the latest texture pack
