### ISSUE TITLE
Injection does nothing

### ISSUE THREAD

**Issue by MysticReaper743** [fligger/FateClient#7]
The resource pack works fine, but once I inject the dll file nothing changes. It's still labeled N/A. I even downloaded the
 x64: vc_redist.x64.exe link you put in the other issue.

P.S. How do you make mods like these? Or is that a trade secret :/ .

**Comment by srmdev** [comment]
Hello so i am not the dev here but if you are using 1.16.100 it won't work as the client has not been updated to the 1.16.100


P.S. You Have to learn game hacking ;) if you want to get started hacking games to make mods/clients just search how to make game hacks with c++

**Comment by srmdev** [comment]
or if you know c# then search how to make game hacks with c# (but you will not find good tuts there 👍 )
